CREATE TABLE CIENTE (
    CD_CLIENTE NUMBER(5) PRIMARY KEY,
    NOME VARCHAR2(10) NOT NULL,
    SOBRENOME VARCHAR2(30) NOT NULL,
    ENDERECO VARCHAR2(40) NOT NULL,
    CIDADE VARCHAR2(15) NOT NULL,
    ESTADO CHAR(2),
    DATA_NASCIMENTO DATE,
    DATA_CADASTRO DATE,
    TELEFONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(40),
    SITUACAO CHAR(1)
);

CREATE TABLE BONUS (
    NR_BONUS NUMBER(5) PRIMARY KEY,
    QT_TEMPO_CA VARCHAR2(20),
    PCT_BONUS_S NUMBER(10,2)
);

CREATE TABLE FUNC_LOJA (
    CD_FUNC NUMBER(5) PRIMARY KEY,
    NOME VARCHAR2(10) NOT NULL,
    SOBRENOME VARCHAR2(30) NOT NULL,
    ENDERECO VARCHAR2(40) NOT NULL,
    CIDADE VARCHAR2(15) NOT NULL,
    ESTADO CHAR(2),
    TELEFONE VARCHAR2(20) NOT NULL,
    SALARIO NUMBER(10,2) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE
);

CREATE TABLE PRODUTO (
    CD_PRODUTO NUMBER(5) PRIMARY KEY,
    DS_PRODUTO VARCHAR2(40),
    TP_PRODUTO VARCHAR2(40),
    VALOR NUMBER(10,2)
);

CREATE TABLE FOLHA_PAGTO (
    NR_ITEM_PAGTO NUMBER(5) PRIMARY KEY,
    ANO_MES VARCHAR2(10),
    SALARIO NUMBER(10,2),
    COMISSAO NUMBER(10,2),
    TOTAL NUMBER(10,2),
    DESCONTOS NUMBER(10,2),
    CD_FUNC NUMBER(5)   
);

ALTER TABLE FOLHA_PAGTO
    ADD CONSTRAINT CD_FUNC_FK FOREIGN KEY(CD_FUNC) REFERENCES FUNC_LOJA(CD_FUNC)


CREATE TABLE ITEM_VENDA (
    NR_ITEM_VENDA NUMBER(5) PRIMARY KEY,
    QTDE_ITEM NUMBER(20),
    SITUACAO_ITEM CHAR(1),
    NR_PEDIDO NUMBER(5),
    CD_PRODUTO NUMBER(5)
);

CREATE TABLE VENDA (
    NR_PEDIDO NUMBER(5) PRIMARY KEY,
    ST_PEDIDO CHAR(1),
    TIPO_PGTO VARCHAR2(10),
    DATA_PEDIDO DATE,
    CD_FUNC NUMBER(5),
    CD_CLIENTE NUMBER(5)
);

ALTER TABLE ITEM_VENDA
    ADD CONSTRAINT NR_PEDIDO_FK FOREIGN KEY(NR_PEDIDO) REFERENCES VENDA(NR_PEDIDO) 
    ADD CONSTRAINT CD_PRODUTO_FK FOREIGN KEY(CD_PRODUTO) REFERENCES PRODUTO(CD_PRODUTO)


ALTER TABLE VENDA
    ADD CONSTRAINT CD_FUNC_FK FOREIGN KEY(CD_FUNC) REFERENCES FUNC_LOJA(CD_FUNC) 
    ADD CONSTRAINT CD_CLIENTE_FK FOREIGN KEY(CD_CLIENTE) REFERENCES CIENTE(CD_CLIENTE)
    
    
DESC ITEM_VENDA

// ia para dados
-- Inserções na tabela CLIENTE
INSERT INTO CIENTE (CD_CLIENTE, NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO, DATA_NASCIMENTO, DATA_CADASTRO, TELEFONE, EMAIL, SITUACAO)
VALUES (1, 'João', 'Silva', 'Rua A, 123', 'São Paulo', 'SP', TO_DATE('1990-05-15', 'YYYY-MM-DD'), SYSDATE, '11999999999', 'joao.silva@email.com', 'A');

-- Inserções na tabela BONUS
INSERT INTO BONUS (NR_BONUS, QT_TEMPO_CA, PCT_BONUS_S)
VALUES (1, '1 ano', 5.00);

-- Inserções na tabela FUNC_LOJA
INSERT INTO FUNC_LOJA (CD_FUNC, NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO, TELEFONE, SALARIO, DATA_INICIO, DATA_FIM)
VALUES (1, 'Maria', 'Santos', 'Rua B, 456', 'Rio de Janeiro', 'RJ', '21988888888', 3000.00, TO_DATE('2020-01-01', 'YYYY-MM-DD'), NULL);

-- Inserções na tabela PRODUTO
INSERT INTO PRODUTO (CD_PRODUTO, DS_PRODUTO, TP_PRODUTO, VALOR)
VALUES (1, 'Camiseta', 'Vestuário', 50.00);

-- Inserções na tabela FOLHA_PAGTO
INSERT INTO FOLHA_PAGTO (NR_ITEM_PAGTO, ANO_MES, SALARIO, COMISSAO, TOTAL, DESCONTOS, CD_FUNC)
VALUES (1, '2023-10', 3000.00, 100.00, 3100.00, 50.00, 1);

-- Inserções na tabela VENDA
INSERT INTO VENDA (NR_PEDIDO, ST_PEDIDO, TIPO_PGTO, DATA_PEDIDO, CD_FUNC, CD_CLIENTE)
VALUES (1, 'A', 'Cartão', SYSDATE, 1, 1);

-- Inserções na tabela ITEM_VENDA
INSERT INTO ITEM_VENDA (NR_ITEM_VENDA, QTDE_ITEM, SITUACAO_ITEM, NR_PEDIDO, CD_PRODUTO)
VALUES (1, 2, 'A', 1, 1);

SELECT * FROM CIENTE
